apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.recurringService.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.recurringService.name }}
    component: recurring-task-service
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.recurringService.name }}
  ports:
  - name: http
    port: {{ .Values.recurringService.service.port }}
    targetPort: 8001
    protocol: TCP
  - name: dapr-http
    port: 3500
    targetPort: 3500
    protocol: TCP
  - name: dapr-grpc
    port: 50001
    targetPort: 50001
    protocol: TCP
